version: '3'
services:
  filessystemapp:
    image: 'stc-project:latest'
    build:
      context: ./
    container_name: filessystemapp
    depends_on:
      - db
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stc
    - SPRING_DATASOURCE_USERNAME=postgres
    - SPRING_DATASOURCE_PASSWORD=thinkmore
    - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=thinkmore
      - POSTGRES_DB=stc