FROM maven:3.8-jdk-11-slim AS MAVEN_BUILD
COPY src ./home/app/src
COPY pom.xml ./home/app
RUN mvn -f /home/app/pom.xml clean package -Dmaven.test.skip=true
FROM adoptopenjdk:11-jre-hotspot
COPY --from=MAVEN_BUILD /home/app/target/stc-project-0.0.1-SNAPSHOT.jar /app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app.jar"]